name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        runtime: [ win-x64, linux-x64, linux-arm64 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Build
        run: |
          dotnet publish ./WeatherBot/WeatherBot.csproj -r ${{ matrix.runtime }} -p:PublishSingleFile=true --self-contained false -o publish/${{ matrix.runtime }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: weather-bot-${{ matrix.runtime }}
          path: publish/${{ matrix.runtime }}/*

  deploy:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: weather-bot-${{ secrets.DEPLOY_ARCH }}
          path: ${{ secrets.DEPLOY_ARCH }}

      - name: Sync to server
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -av
          path: ${{ secrets.DEPLOY_ARCH }}/*
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}

      - name: Replace files and restart
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: ${{ secrets.DEPLOY_SCRIPT }}
