name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        runtime: [ win-x64, linux-x64, linux-arm64 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Build
        run: |
          dotnet publish ./WeatherBot/WeatherBot.csproj -r ${{ matrix.runtime }} -p:PublishSingleFile=true --self-contained false -o publish/${{ matrix.runtime }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: weather-bot-${{ matrix.runtime }}
          path: publish/${{ matrix.runtime }}/*
